version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27030:27017
    volumes:
      - mongodata:/data/db
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    expose:
      - 27030

  bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      ENV: dev
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
      TOKEN: ${BOT_TOKEN}
      GUILD_ID_WITH_COMMANDS: ${BOT_GUILD_ID}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      # - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mongodata:
    driver: local